In [1]:
print('hello Anaconda')

hello Anaconda


In [2]:
print(np.array([1,2,3]))

NameError: name 'np' is not defined

In [3]:
print(numpy.array([1,2,3]))

NameError: name 'numpy' is not defined

In [5]:
import numpy as np
print(np.array([1,2,3]))
print(np.array([1,2,3],[4,5,6]))

[1 2 3]


TypeError: data type not understood

In [15]:
import numpy as np
print(np.array([(1,2,3),(4,5,6)]))
print(np.zeros((3,4)))
print(np.zeros((3,4,2)))
print(np.eye(2))
print(np.diag([1,2,3,4]))
print(np.full((2,3),10))
print(np.empty((2,3)))
print(np.logspace(0,2,200))

[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[1. 0.]
 [0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[10 10 10]
 [10 10 10]]
[[0. 0. 0.]
 [0. 0. 0.]]
[  1.           1.0234114    1.0473709    1.07189132   1.0969858
   1.12266777   1.148951     1.17584955   1.20337784   1.2315506
   1.26038293   1.28989026   1.3200884    1.35099352   1.38262217
   1.4149913    1.44811823   1.48202071   1.51671689   1.55222536
   1.58856513   1.62575567   1.66381689   1.70276917   1.74263339
   1.78343088   1.82518349   1.8679136    1.91164408   1.95639834
   2.00220037   2.04907469   2.0970464    2.1461412    2.19638537
   2.24780583   2.30043012   2.35428641   2.40940356   2.46581108
   2.52353917   2.58261876   2.64308149   2.70495973   2.76828663
   2.8330961    2.89942285   2.96730241   3.03677112   3.10786619
   3.18062569   3.2550886    3.331294

In [17]:
import numpy as np

In [18]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [19]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [20]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr3 = np.arange(1,10,3)
arr3

array([1, 4, 7])

In [28]:
arr4 = np.zeros((4,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
arr5 = np.ones((4,3))
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
arr6 = np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr7 = np.diag([1,2,3,4])
arr7

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [46]:
np.logspace(1,3,3)

array([  10.,  100., 1000.])

In [50]:
np.random.randint(0,10)

2

In [51]:
np.random.randn(10,5)

array([[-2.01244745, -1.51093332, -0.09784826,  0.07544367,  0.62578336],
       [-0.84580255, -0.14861652,  0.23646293,  1.65014383, -0.15678051],
       [-0.52081844,  1.71160737,  0.06716134,  0.81616919,  1.54249566],
       [ 0.57543677,  0.8855896 ,  0.68277958, -0.07163191, -0.38337869],
       [ 0.22106913, -0.1333473 , -1.64773385, -0.36385406, -0.20519807],
       [ 0.48632106,  0.55321882, -0.06762365, -0.33604607, -2.18563701],
       [ 1.09602701,  0.38141445,  0.35514175,  0.56740669, -1.5252739 ],
       [ 0.86630689, -0.48315845, -0.31927825, -0.11580369, -0.4306802 ],
       [ 1.57887592,  0.60606444, -0.39318596,  0.15070316,  1.29141527],
       [ 0.24094126,  0.47043547, -0.57780411,  0.22059034, -0.10741357]])

In [52]:
np.random.rand(10,5)

array([[0.83807005, 0.90167934, 0.93441874, 0.94835607, 0.92006223],
       [0.83871368, 0.18820775, 0.16735321, 0.44792284, 0.97112189],
       [0.30738326, 0.55756663, 0.34715703, 0.6473262 , 0.34721873],
       [0.81517445, 0.3518275 , 0.31192357, 0.87425478, 0.27373438],
       [0.76839554, 0.83229646, 0.19765351, 0.57568064, 0.52313918],
       [0.43070476, 0.83022772, 0.71882925, 0.90397653, 0.5066422 ],
       [0.03171427, 0.90128219, 0.88916389, 0.09476895, 0.78623354],
       [0.92987867, 0.30833434, 0.94470969, 0.61604086, 0.66401831],
       [0.42602565, 0.98479147, 0.79655268, 0.25853978, 0.0457521 ],
       [0.90955696, 0.66091789, 0.63973165, 0.03540481, 0.20210046]])

In [56]:
arr8 = np.ones((1000,5))
arr8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       ...,
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
arr8 = np.ones((1000,5))
np.set_printoptions(threshold=np.inf)
arr8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1.

In [59]:
arr8.ndim

2

In [60]:
arr8.shape

(1000, 5)

In [61]:
arr8.size

5000

In [63]:
arr8.dtype

dtype('float64')

In [64]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr2[:,:2]

array([[1, 2],
       [4, 5]])

In [85]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
arr2[(0,1),(1,1)]

array([2, 5])

In [89]:
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [99]:
mask = np.array([1,0,1],dtype=np.bool)
arr4[mask,2]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 3

In [104]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [103]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
np.arange(12).reshape(3,4).ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
np.arange(12).reshape(3,4).flatten('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [110]:
arr = np.arange(12).reshape(3,4)
arr*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [111]:
arr1 = np.mat("1 2 3;4 5 6;7 8 9")

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [112]:
arr10 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [117]:
arr1 * arr2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [120]:
np.dot(arr1,arr10)

NameError: name 'arr10' is not defined

In [121]:
arr10 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [122]:
arr10

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [123]:
np.dot(arr10,arr1)

matrix([[14, 32, 50]])

In [124]:
arr1 = np.mat("1 2 3;4 5 6;7 8 9")
arr10 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
np.dot(arr1,arr10)

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [125]:
arr1 = np.mat("1 2 3;4 5 6;7 8 9")
arr10 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
arr1*arr10

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [126]:
matr1 = np.mat("1 2 3 4;5 6 7 8;9 10 11 12")
matr1[np.where(matr1>5)]

matrix([[ 6,  7,  8,  9, 10, 11, 12]])

In [128]:
arr = np.arange(5)
arr
np.tile(arr,3)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [129]:
arr = np.random.randint(0,10,size=(3,3))
arr.repeat(2,axis=0)

array([[1, 5, 7],
       [1, 5, 7],
       [3, 9, 8],
       [3, 9, 8],
       [5, 4, 0],
       [5, 4, 0]])

In [130]:
arr = np.random.randint(0,10,size=(3,3))
arr.repeat(2,axis=1)

array([[0, 0, 4, 4, 1, 1],
       [8, 8, 6, 6, 8, 8],
       [4, 4, 6, 6, 6, 6]])

In [131]:
np.save('demo.npy',arr)

In [132]:
np.load("demo.npy")

array([[0, 4, 1],
       [8, 6, 8],
       [4, 6, 6]])

In [133]:
np.savetxt('demo1',arr)